CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251027160017_Initial') THEN
    CREATE TABLE customers (
        "CustomerId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Address" text NOT NULL,
        "Phone" text NOT NULL,
        "ContactPerson" text NOT NULL,
        CONSTRAINT "PK_customers" PRIMARY KEY ("CustomerId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251027160017_Initial') THEN
    CREATE TABLE items (
        "ItemId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Price" integer NOT NULL,
        "Delivery" boolean NOT NULL,
        "Description" text NOT NULL,
        CONSTRAINT "PK_items" PRIMARY KEY ("ItemId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251027160017_Initial') THEN
    CREATE TABLE orders (
        "OrderId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "ItemId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "OrderDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_orders" PRIMARY KEY ("OrderId"),
        CONSTRAINT "FK_orders_customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES customers ("CustomerId") ON DELETE CASCADE,
        CONSTRAINT "FK_orders_items_ItemId" FOREIGN KEY ("ItemId") REFERENCES items ("ItemId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251027160017_Initial') THEN
    CREATE INDEX "IX_orders_CustomerId" ON orders ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251027160017_Initial') THEN
    CREATE INDEX "IX_orders_ItemId" ON orders ("ItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251027160017_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251027160017_Initial', '9.0.10');
    END IF;
END $EF$;
COMMIT;

